Add bookings
sashajaaa/java-shareit pull request #2
Opened 2023-05-12 17:12 UTC by sashajaaa

2023-05-13 21:09 UTC, kalitva requested changes

2023-05-13 21:09 UTC, kalitva commented on pom.xml
> +		<dependency>
Хибернейт уже подтягивается вместе с data-jpa

2023-05-13 21:09 UTC, kalitva commented on pom.xml
> +			<artifactId>spring-boot-starter-data-jdbc</artifactId>
jdbc тоже

2023-05-13 21:09 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    void update(BookingStatus status, Long bookingId);
Стоит пожалуй назвать `updateStatus`, а вообще для обновления объекта обычно используется `save`

2023-05-13 21:09 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByBookerIdOrderByStartDesc(long id);
Вместо определения всех этих методов можно использовать `Specification` фильтры, это необязательно но будет очень полезно знать

https://spring.io/blog/2011/04/26/advanced-spring-data-jpa-specifications-and-querydsl

2023-05-13 21:09 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllBookingsOwner(Long ownerId);
В большинстве случаев можно обойтись без `@Query`, например здесь - `findByOwnerId(ownerId, Sort sort)`

2023-05-13 21:09 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        if (approve) {
Как насчет что-то типа

```java
BookingStatus status = approve ? APPROVED : REJECTED;
booking.setTatus(status);
bookingRepository.save(booking);
```

2023-05-13 21:09 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private ShortItemBookingDto lastBooking;
Никаких dto в классах ентити! Используй `Booking`

2023-05-13 21:09 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +                .peek((i) -> CommentMapper.toDtoList(commentRepository.findAllByItemId(i.getId())))
`peek` не рекомендуется в продакшен коде, почитай javadoc метода. Просто чтобы знал, можешь оставить если хочешь

2023-05-13 21:09 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
> -@Component
Зачем удалил? Статика - зло

2023-05-13 21:09 UTC, kalitva commented on src/main/resources/application.properties
>  spring.datasource.url=jdbc:h2:mem:shareit
Желательно чтобы ты попробовал подключиться к postgres

2023-05-13 21:09 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> -            return Collections.emptyList();
Это правильнее было

2023-05-15 09:52 UTC, sashajaaa commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        if (approve) {
Это очень критично? Все тесты со статусами сыпаться начинают...

2023-05-15 09:53 UTC, sashajaaa commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllBookingsOwner(Long ownerId);
А очень плохо с Query? Нельзя так оставить?

2023-05-16 06:01 UTC, kalitva approved these changes

2023-05-16 06:01 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +    public static OutputBookingDto toBookingDto(Booking booking) {
Сделай методы инстанс и инжекти мапперы спрингом

2023-05-16 06:01 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query("SELECT b FROM Booking b "
`findByOwnerId --> findByItemOwnerId` и должно заработать без `@Query`

2023-05-16 06:01 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByBookerIdAndStatusIsOrderByStartDesc(Long id, BookingStatus status);
Слоао `All` необязательно, обычно его не используют

2023-05-16 06:01 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +    public static ItemDto toItemDto(Item item) {
Без static

2023-05-16 06:01 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    void save(BookingStatus status, Long bookingId);
Не вижу особого смысла переопределять родительский `save`

2023-05-17 14:40 UTC, sashajaaa commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query("SELECT b FROM Booking b "
не заработало

2023-05-17 15:16 UTC, merged